### ISSUE TITLE
Not recognized as an internal or external command

### ISSUE THREAD

**Issue by AndreiMunteanu2911** [MonoScyron/md-auto#1]
Hi, when I try running the .bat file after opening the game I get this error
![Capture](https://user-images.githubusercontent.com/94112270/227845398-de88e79a-24b4-4f3e-8c2c-9e9cd2e6e5d2.PNG)
I assume it has do to something with the folder name having a blank space between Limbus and Company

**Comment by MonoScyron** [comment]
That's the issue, yes. Since there's no need for the bat file to be in the Limbus Company folder, please clone the code in a folder with no spaces.
